-- Baseline inicial del esquema StrengthLab.
-- Generado a partir de las entidades JPA (Hibernate metadata) y formateado.
-- A partir de aqui, todo cambio de esquema va en una nueva migracion V2, V3, ...

create table exercise (
    id              bigint generated by default as identity,
    base_name       varchar(100) not null,
    main_pattern    varchar(30)  not null check (main_pattern in ('NONE','SQUAT','BENCH','DEADLIFT','PRESS','OLY','ACCESSORY')),
    setup           varchar(30)  check (setup in ('STANDARD','LOWBAR','HIGHBAR','FRONT','ZERCHER','SSB','CAMBERED','SPLIT','ONE_ARM','SNATCH_GRIP','CLOSE_GRIP','BOX')),
    stance          varchar(30)  check (stance in ('NARROW','MEDIUM','WIDE','SUMO','CONVENTIONAL','NONE','LARSEN','PARALYMPIC')),
    grip            varchar(30)  check (grip in ('CLOSE','MEDIUM','WIDE','SNATCH','CLEAN','NEUTRAL','PRONATED','SUPINATED','MIXED','NONE')),
    implement       varchar(30)  check (implement in ('BARBELL','DUMBBELL','KETTLEBELL','TRAP_BAR','SAFETY_BAR','CAMBERED_BAR','SWISS_BAR','PLATES','CABLE','MACHINE','SMITH','RINGS','BODYWEIGHT','LANDMINE','PULLUP_BAR')),
    height_mode     varchar(30)  check (height_mode in ('NONE','DEFICIT','SUPERHABIT','BLOCK','PINS','BOARD')),
    height_length   integer,
    loading_method  varchar(30)  check (loading_method in ('NONE','BANDS','CHAINS','BOTH')),
    loading_unit    varchar(10)  check (loading_unit in ('KG','PERCENT','RANGE','UNKNOWN')),
    pause_seconds   integer,
    tempo           varchar(20),
    bar             varchar(50),
    resistance      varchar(50),
    style           varchar(50),
    equipment       varchar(100),
    notes           varchar(500),
    primary key (id)
);

create table training_session_template (
    id                  bigint generated by default as identity,
    block_name          varchar(100) not null,
    week_number         integer      not null check (week_number >= 1),
    day_in_week         integer      not null check (day_in_week >= 1 and day_in_week <= 7),
    conjugate_day_type  varchar(255) not null check (conjugate_day_type in ('ME_UPPER','ME_LOWER','DE_UPPER','DE_LOWER','RE_UPPER','RE_LOWER')),
    notes               varchar(1000),
    primary key (id)
);

create table training_set_template (
    id                      bigint generated by default as identity,
    session_template_id     bigint,
    exercise_id             bigint,
    display_order           integer check (display_order >= 1 and display_order <= 10),
    target_sets             integer check (target_sets >= 1 and target_sets <= 5),
    target_reps             integer check (target_reps >= 1 and target_reps <= 50),
    target_weight           float(53) check (target_weight >= 1 and target_weight <= 1000),
    target_intensity        integer,
    target_intensity_type   varchar(255) check (target_intensity_type in ('RIR','RPE','PERCENTAGE')),
    rest                    varchar(255),
    notes                   varchar(500),
    primary key (id)
);

create table workout_session (
    id                              bigint generated by default as identity,
    session_date                    date not null,
    training_session_template_id    bigint,
    primary key (id)
);

create table workout_entry (
    id                  bigint generated by default as identity,
    workout_session_id  bigint not null,
    exercise_id         bigint not null,
    is_warmup           boolean,
    actual_sets         integer,
    actual_reps         integer,
    actual_plate_weight float(53),
    actual_rir_or_rpe   varchar(255),
    notes               varchar(500),
    primary key (id)
);

create table workout_set (
    id                  bigint generated by default as identity,
    workout_entry_id    bigint not null,
    set_number          integer not null check (set_number >= 1),
    reps                integer not null,
    weight              float(53),
    intensity_value     integer check (intensity_value >= 0 and intensity_value <= 11),
    intensity_type      varchar(255) check (intensity_type in ('RIR','RPE','PERCENTAGE')),
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    primary key (id)
);

alter table training_set_template add constraint fk_set_template_exercise foreign key (exercise_id) references exercise;
alter table training_set_template add constraint fk_set_template_session  foreign key (session_template_id) references training_session_template;
alter table workout_entry        add constraint fk_entry_exercise         foreign key (exercise_id) references exercise;
alter table workout_entry        add constraint fk_entry_session          foreign key (workout_session_id) references workout_session;
alter table workout_session      add constraint fk_session_template       foreign key (training_session_template_id) references training_session_template;
alter table workout_set          add constraint fk_set_entry              foreign key (workout_entry_id) references workout_entry;
