
name: test
on :
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:12
        ports:
          - 5432:5432
        options:
           --health-cmd pg_ready -U postgres
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5

    env:
      SPRING_PROFILES_ACTIVE: test
      DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: merge PR
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          fi